# This file is part of Edgehog.
#
# Copyright 2025 SECO Mind Srl
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

name: main
on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - release-*
  push:
    branches:
      - main
      - release-*
# Spend CI time only on latest ref
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
defaults:
  run:
    shell: bash
jobs:
  comment-changelog:
    if: "${{ github.event_name == 'pull_request' }}"
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: install git-cliff
        uses: taiki-e/install-action@v2.57.1
        with:
          tool: git-cliff
      - name: create changelog comment
        run: |
          ./scripts/changelog-comment.sh "$FROM" "$TO" "$PR"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FROM: ${{ github.event.pull_request.base.sha }}
          TO: ${{ github.event.pull_request.head.sha }}
          PR: ${{ github.event.pull_request.number }}
  generate-changelog:
    if: "${{ github.event_name == 'push' }}"
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: install git-cliff
        uses: taiki-e/install-action@v2.57.1
        with:
          tool: git-cliff
      - name: generate changelog comment
        run: |
          git cliff > CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v6.0.1
        with:
          commit_message: "chore(CHANGELOG): auto-generate changelog"
          branch: ${{ github.ref_name }}
          file_pattern: "CHANGELOG.md"
